# Form implementation generated from reading ui file 'task_manager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(756, 723)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(main_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabs = QtWidgets.QTabWidget(parent=main_window)
        self.tabs.setObjectName("tabs")
        self.tab_processes = QtWidgets.QWidget()
        self.tab_processes.setObjectName("tab_processes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_processes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_processes = QtWidgets.QTableWidget(parent=self.tab_processes)
        self.table_processes.setObjectName("table_processes")
        self.table_processes.setColumnCount(9)
        self.table_processes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processes.setHorizontalHeaderItem(8, item)
        self.verticalLayout.addWidget(self.table_processes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_endtask = QtWidgets.QPushButton(parent=self.tab_processes)
        self.button_endtask.setMinimumSize(QtCore.QSize(100, 25))
        self.button_endtask.setObjectName("button_endtask")
        self.horizontalLayout.addWidget(self.button_endtask)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabs.addTab(self.tab_processes, "")
        self.tab_cpu = QtWidgets.QWidget()
        self.tab_cpu.setObjectName("tab_cpu")
        self.tabs.addTab(self.tab_cpu, "")
        self.tab_memory = QtWidgets.QWidget()
        self.tab_memory.setObjectName("tab_memory")
        self.tabs.addTab(self.tab_memory, "")
        self.tab_network = QtWidgets.QWidget()
        self.tab_network.setObjectName("tab_network")
        self.tabs.addTab(self.tab_network, "")
        self.verticalLayout_2.addWidget(self.tabs)

        self.retranslateUi(main_window)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Task Manager"))
        item = self.table_processes.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "User"))
        item = self.table_processes.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Pid"))
        item = self.table_processes.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Name"))
        item = self.table_processes.horizontalHeaderItem(3)
        item.setText(_translate("main_window", "State"))
        item = self.table_processes.horizontalHeaderItem(4)
        item.setText(_translate("main_window", "Threads"))
        item = self.table_processes.horizontalHeaderItem(5)
        item.setText(_translate("main_window", "CPU"))
        item = self.table_processes.horizontalHeaderItem(6)
        item.setText(_translate("main_window", "Mem"))
        item = self.table_processes.horizontalHeaderItem(7)
        item.setText(_translate("main_window", "Start"))
        item = self.table_processes.horizontalHeaderItem(8)
        item.setText(_translate("main_window", "Running"))
        self.button_endtask.setText(_translate("main_window", "End Task"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_processes), _translate("main_window", "Processes"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_cpu), _translate("main_window", "CPU"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_memory), _translate("main_window", "Memory"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_network), _translate("main_window", "Network/Disk"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QWidget()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())
